services:
  vpn:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DISABLE_LOGS: 1
    ports:
      - "1194:1194/udp"
      - "443:443/tcp"
    volumes:
      - type: bind
        source: ./config
        target: /etc/openvpn
    privileged: true
    restart: "always"
    logging:
      driver: none

